version: 2
build:
  os: ubuntu-22.04
  jobs:
    post_checkout:
      - echo post_checkout
      - git fetch --unshallow  || true
    pre_system_dependencies:
      - echo pre_system_dependencies
    post_system_dependencies:
      - echo post_system_dependencies
    pre_create_environment:
      - echo pre_create_environment
    post_create_environment:
      - echo post_create_environment
    pre_install:
      - echo pre_install
      - python -m pip install --upgrade pip
    post_install:
      - echo post_install
    pre_build:
      - echo pre_build
    post_build:
      - echo post_build
  tools:
    python: "3"
python:
   install:
   - requirements: requirements.txt

sphinx:
  configuration: docs/sphinx/conf.py
  builder: html
