version: 2
build:
  os: ubuntu-22.04
  jobs:
    post_checkout:
      - echo post_checkout
      - git fetch --unshallow  || true
    pre_system_dependencies:
      - echo pre_system_dependencies
      - |
        # Test multi-line script
        if test -n "A"; then echo "B"; fi
    post_system_dependencies:
      - echo post_system_dependencies
    pre_create_environment:
      - echo pre_create_environment
    post_create_environment:
      - echo post_create_environment
    pre_install:
      - echo pre_install
    post_install:
      - echo post_install
    pre_build:
      - echo pre_build
      - python -m sphinx -b linkcheck docs/ _build/linkcheck
      - sed **/*.rst --in-place --expression "s|{VERSION}|${READTHEDOCS_VERSION_NAME}|g"
    post_build:
      - echo post_build
      - echo $READTHEDOCS_OUTPUT
      - find $READTHEDOCS_OUTPUT
  tools:
    python: "3"
python:
   install:
   - requirements: docs/sphinx/requirements.txt

sphinx:
  configuration: docs/sphinx/conf.py
  builder: html
