version: 2
python:
   install:
   - requirements: docs/sphinx/requirements.txt
build:
  jobs:
    post_create_environment:
      - echo `date`
sphinx:
  configuration: docs/sphinx/conf.py
  builder: html
